server.port=9191
#Add Routing
spring.cloud.gateway.server.webflux.routes[0].id=PRODUCTSERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCTSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/product/**
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.name=PRODUCTSERVICE
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.fallbackUri=forward:/productFallback

spring.cloud.gateway.server.webflux.routes[1].id=ORDER
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDER
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/order/**

spring.cloud.gateway.server.webflux.routes[2].id=PAYMENTSERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/payment/**

management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted
 
#Circuit Breaker
resilience4j.circuitbreaker.instances.PRODUCTSERVICE.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.PRODUCTSERVICE.slidingWindowSize=6
resilience4j.circuitbreaker.instances.PRODUCTSERVICE.failureRateThreshold=50
resilience4j.circuitbreaker.instances.PRODUCTSERVICE.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.PRODUCTSERVICE.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.PRODUCTSERVICE.minimumNumberOfCalls=5

#Spring Security
spring.security.user.name=admin
spring.security.user.password=password123
